spring:
  config:
    activate:
      on-profile: default
  profiles:
    include:
      - key
      - mail
      - security
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
---

spring:
  config:
    activate:
      on-profile: test
  profiles:
    include:
      - key
      - mail
      - securitylocal
  jpa:
    hibernate:
      ddl-auto: create

    show-sql: true
---